defaults:
  - domain_randomization: default_dom_rand_conf
  - override hydra/job_logging: default
  - override hydra/launcher: basic

hydra:
  mode: MULTIRUN
  job_logging: {}
  hydra_logging: {}
  sweeper:
    params:
#      experiment.learnable_std: true, false
#      experiment.init_std: 0.1, 0.2
#      experiment.num_steps: 10, 20
#      experiment.update_epochs: 4
#      experiment.clip_eps: 0.2, 0.05
      # env_params
      experiment.total_timesteps: 50e7, 100e7
      experiment.hidden_layers: \[1024\, 512\, 1256\], \[8421\, 45\]

wandb:
  project: "real_unitreeh1_lafan1"

experiment:
  task_factory:
    name: LAFAN1ImitationFactory
    params:
      dataset_name:
      #- walk1_subject1
      - walk1_subject2
      #- walk1_subject5
      #- walk2_subject4
      #- walk3_subject2
  env_params:
    env_name: MjxUnitreeH1
    headless: True
    horizon: 1000
    goal_type: GoalTrajMimic
    goal_params:
      visualize_goal: true
    reward_type: MimicReward
    reward_params:
      action_out_of_bounds_coeff: 0.01
      joint_acc_coeff: 2e-7
      joint_torque_coeff: 2e-5
      action_rate_coeff: 5e-2
      qpos_w_sum: 0.4
      qvel_w_sum: 0.2
      rpos_w_sum: 0.5
      rquat_w_sum: 0.3
      rvel_w_sum: 0.1
      sites_for_mimic:
        - upper_body_mimic
        - left_hand_mimic
        - left_foot_mimic
        - right_hand_mimic
        - right_foot_mimic
    #terrain_type: RoughTerrain
    domain_randomization_type: DefaultRandomizer
    domain_randomization_params: ${domain_randomization}
    #timestep: 0.004 # 250 Hz
    #n_substeps: 5   # 50 Hz
    observation_spec:
      - type: ProjectedGravityVector
        obs_name: q_root
        xml_name: root
      - type: JointPosArray
        obs_name: joint_positions
        xml_names:
          - back_bkz
          - l_arm_shy
          - l_arm_shx
          - l_arm_shz
          - left_elbow
          - r_arm_shy
          - r_arm_shx
          - r_arm_shz
          - right_elbow
          - hip_flexion_r
          - hip_adduction_r
          - hip_rotation_r
          - knee_angle_r
          - ankle_angle_r
          - hip_flexion_l
          - hip_adduction_l
          - hip_rotation_l
          - knee_angle_l
          - ankle_angle_l
      - type: FreeJointVel
        obs_name: dq_root
        xml_name: root
      - type: JointVelArray
        obs_name: joint_velocities
        xml_names:
          - back_bkz
          - l_arm_shy
          - l_arm_shx
          - l_arm_shz
          - left_elbow
          - r_arm_shy
          - r_arm_shx
          - r_arm_shz
          - right_elbow
          - hip_flexion_r
          - hip_adduction_r
          - hip_rotation_r
          - knee_angle_r
          - ankle_angle_r
          - hip_flexion_l
          - hip_adduction_l
          - hip_rotation_l
          - knee_angle_l
          - ankle_angle_l
      - type: LastAction
        obs_name: last_action
    action_spec:
      - back_bkz_actuator
      - l_arm_shy_actuator
      - l_arm_shx_actuator
      - l_arm_shz_actuator
      - left_elbow_actuator
      - r_arm_shy_actuator
      - r_arm_shx_actuator
      - r_arm_shz_actuator
      - right_elbow_actuator
      - hip_flexion_r_actuator
      - hip_adduction_r_actuator
      - hip_rotation_r_actuator
      - knee_angle_r_actuator
      - ankle_angle_r_actuator
      - hip_flexion_l_actuator
      - hip_adduction_l_actuator
      - hip_rotation_l_actuator
      - knee_angle_l_actuator
      - ankle_angle_l_actuator
    control_type: ${control_config.position_control.control_type}
    control_params: ${control_config.position_control.control_params}
  hidden_layers: [512, 256]
  lr: 1e-4
  len_obs_history: 5
  num_envs: 2048
  num_steps: 20
  total_timesteps: 5e6
  update_epochs: 4
  num_minibatches: 32
  gamma: 0.99
  gae_lambda: 0.95
  clip_eps: 0.2
  init_std: 0.8
  learnable_std: True
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  activation: tanh
  anneal_lr: false
  weight_decay: 0.0
  normalize_env: true
  debug: false
  n_seeds: 1  # while automatically take seeds from 1 to n_seeds
  vmap_across_seeds: true
  validation:
    active: true
    num_steps: 100
    num_envs: 100
    num: 10 # set to 0 to disable validation
    # if none of the following is set, only the mean reward and episode length is logged
    quantities: # quantities to be used for the distance measures below
      - JointPosition
      - JointVelocity
      - RelSitePosition
      - RelSiteVelocity
      - RelSiteOrientation
    measures:
      - EuclideanDistance
      - DynamicTimeWarping
      - DiscreteFrechetDistance
    rel_site_names:
      - upper_body_mimic
      - left_hand_mimic
      - left_foot_mimic
      - right_hand_mimic
      - right_foot_mimic
    joints_to_ignore:
      - pelvis_tx
      - pelvis_tz
      - pelvis_ty
      - pelvis_tilt
      - pelvis_list
      - pelvis_rotation


# Define control subconfigs
control_config:
  position_control:
    control_type: PDControl
    control_params:
      p_gain:
        - 300  # back_bkz_actuator -> torso
        - 100  # l_arm_shy_actuator -> shoulder
        - 100  # l_arm_shx_actuator -> shoulder
        - 100  # l_arm_shz_actuator -> shoulder
        - 100  # left_elbow_actuator -> elbow
        - 100  # r_arm_shy_actuator -> shoulder
        - 100  # r_arm_shx_actuator -> shoulder
        - 100  # r_arm_shz_actuator -> shoulder
        - 100  # right_elbow_actuator -> elbow
        - 200  # hip_flexion_r_actuator -> hip_pitch
        - 200  # hip_adduction_r_actuator -> hip_roll
        - 200  # hip_rotation_r_actuator -> hip_yaw
        - 300  # knee_angle_r_actuator -> knee
        - 40   # ankle_angle_r_actuator -> ankle
        - 200  # hip_flexion_l_actuator -> hip_pitch
        - 200  # hip_adduction_l_actuator -> hip_roll
        - 200  # hip_rotation_l_actuator -> hip_yaw
        - 300  # knee_angle_l_actuator -> knee
        - 40   # ankle_angle_l_actuator -> ankle
      d_gain:
        - 6  # back_bkz_actuator -> torso
        - 2  # l_arm_shy_actuator -> shoulder
        - 2  # l_arm_shx_actuator -> shoulder
        - 2  # l_arm_shz_actuator -> shoulder
        - 2  # left_elbow_actuator -> elbow
        - 2  # r_arm_shy_actuator -> shoulder
        - 2  # r_arm_shx_actuator -> shoulder
        - 2  # r_arm_shz_actuator -> shoulder
        - 2  # right_elbow_actuator -> elbow
        - 5  # hip_flexion_r_actuator -> hip_pitch
        - 5  # hip_adduction_r_actuator -> hip_roll
        - 5  # hip_rotation_r_actuator -> hip_yaw
        - 6  # knee_angle_r_actuator -> knee
        - 2  # ankle_angle_r_actuator -> ankle
        - 5  # hip_flexion_l_actuator -> hip_pitch
        - 5  # hip_adduction_l_actuator -> hip_roll
        - 5  # hip_rotation_l_actuator -> hip_yaw
        - 6  # knee_angle_l_actuator -> knee
        - 2  # ankle_angle_l_actuator -> ankle

  torque_control:
    control_type: DefaultControl
    control_params:
