# gravity
randomize_gravity: true
gravity_range: [9.51, 10.11]

# geom properties
randomize_geom_friction_tangential: true
geom_friction_tangential_range: [0.8, 1.2]
randomize_geom_friction_torsional: true
geom_friction_torsional_range: [0.003, 0.007]
randomize_geom_friction_rolling: true
geom_friction_rolling_range: [0.00008, 0.00012]
randomize_geom_damping: true
geom_damping_range: [0.015, 0.025]
randomize_geom_stiffness: true
geom_stiffness_range: [0.9, 1.1]

# joint properties
randomize_joint_friction: true
joint_friction_range: [0.0, 0.1]
randomize_joint_damping: true
joint_damping_range: [0.08, 0.12]
randomize_joint_stiffness: true
joint_stiffness_range: [0.9, 1.1]
randomize_joint_friction_loss: true
joint_friction_loss_range: [0.0, 0.2]
