# gravity
randomize_gravity: true
gravity_range: [9.51, 10.11]

# geom properties
randomize_geom_friction_tangential: true
geom_friction_tangential_range: [0.8, 1.2]
randomize_geom_friction_torsional: true
geom_friction_torsional_range: [0.003, 0.007]
randomize_geom_friction_rolling: true
geom_friction_rolling_range: [0.00008, 0.00012]
randomize_geom_damping: true
geom_damping_range: [0.015, 0.025]
randomize_geom_stiffness: true
geom_stiffness_range: [0.9, 1.1]

# joint properties
randomize_joint_friction: true
joint_friction_range: [0.01, 0.5]
randomize_joint_damping: true
joint_damping_range: [0.3, 1.5]  
randomize_joint_stiffness: true
joint_stiffness_range: [0.9, 1.1]
randomize_joint_friction_loss: true
joint_friction_loss_range: [0.01, 0.5]
randomize_joint_armature: true
joint_armature_range: [0.0001, 0.05] 

#base mass
randomize_base_mass: true
base_mass_to_add_range: [-2.0, 2.0]

#COM
randomize_com_displacement: true
com_displacement_range: [-0.15, 0.15]

#link mass
randomize_link_mass: true
link_mass_multiplier_range: {
                              "root_body":[0.5, 1.9],
                              "other_bodies":[0.8, 1.2],
                            }

#PD Gains
add_p_gains_noise: true
add_d_gains_noise: true
p_gains_noise_scale: 0.1
d_gains_noise_scale: 0.1

#Observation Noise
add_joint_pos_noise: true
joint_pos_noise_scale: 0.01
add_joint_vel_noise: true
joint_vel_noise_scale: 0.5
add_gravity_noise: true
gravity_noise_scale: 0.05
add_free_joint_lin_vel_noise: true
lin_vel_noise_scale: 0.1
add_free_joint_ang_vel_noise: true
ang_vel_noise_scale: 0.3          